version: 0.2
phases:
  install:
    commands:
      - npm install -g @angular/cli  # Install Angular CLI globally
      - echo Installing dependencies
      - npm install
  build:
    commands:
      - echo Building the project
      - ng build
      - echo Creating ZIP file
      - cd dist/  # Adjust if necessary
      - zip -r ../build-output.zip .  # Create ZIP file
artifacts:
  files:
    - build-output.zip
